default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: csf_d
  username: csf
  password: csf

test:
  <<: *default
  database: csf_t
  username: csf
  password: csf
